### ISSUE TITLE
Downsampling support

### ISSUE THREAD

**Issue by arthurprs** [koush/ion#111]
By efficiently decoding the image to fit into the target imageview (downsample) the library can save lots of memory.

**Comment by stevep99** [comment]
This feature could be supported by allowing user to supply the downscaling parameter if known. 

This would be for cases where the size of the image and of the target imageview are known at runtime due to the developer's design decisions. For example, I have a case where the image is a full-screen background image. SInce I know the screen dimensions of the device, I can easily calculate the required downscale factor. But Ion doesn't provide a way for me to use this AFAIK :(

**Comment by koush** [comment]
I actually ended up implementing this btw.

**Comment by koush** [comment]
I am fetching at onDraw time, so i Know the image view bounds, and can figure out sampling parameters.
