### ISSUE TITLE
ImageView ScaleType

### ISSUE THREAD

**Issue by jehad-suliman** [koush/ion#508]
with the new version of Ion some of the images not showing Correctly 
it shows the Left top of the image 
this problem shows in a ListView 
 this problem not showing on all images 
its only on some of them i dont use any scale type for the image

**Comment by koush** [comment]
Video or application that shows the issue?

**Comment by schwiz** [comment]
Been seeing this since 209. Referenced in https://github.com/koush/ion/issues/375#issuecomment-78203425

**Comment by koush** [comment]
@schwiz are you also seeing this in listviews, or outside of listviews?

**Comment by schwiz** [comment]
In RecylerView I get the zoomed in behavior I described. Getting the small
image in upper left corner outside of RecylerView.

**Comment by koush** [comment]
@schwiz screenshot or something? Also an xml snpippet of the imageview and it's container?

**Comment by schwiz** [comment]
Happy to do that. Wont have time until tomorrow though.

**Comment by schwiz** [comment]
Okay so here are the layout files you requested. Also a screenshot of the top-left image thing and a video of the zoom in thing. The video/image aren't public I just shared them with the google plus account I have for you. Let me know if you need more info or have problems seeing them.

https://gist.github.com/schwiz/95e4627f8e5e3e7abd5e
https://plus.google.com/photos/115761414216887564109/albums/6125442873019242913?authkey=CLzau_rQ2b_39gE

**Comment by koush** [comment]
So, I use this:

**Comment by koush** [comment]
I'll bet if you disable smart size, this issue will go away.

smartSize does some (generally) smart stuff for imageviews to minimize memory usage:
When loading the bitmap, it checks the imageview canvas size to see what sampleSize it should use when decoding.

However, since your framelayout may be returning odd values for the width/height and throwing things off. Not sure, don't really want to debug into it too much until you get back to me w/ my code sample :)

Should be fairly easy to drop in and will give you the same layout results as what you have now.

**Comment by koush** [comment]
oh shit i think i just repro'd this in my code.

**Comment by koush** [comment]
5ca33be

**Comment by schwiz** [comment]
Thank for the fix you had me worried there for a second.   :-) 
Things seem to be back to normal!
