### ISSUE TITLE
Is SNI supported?

### ISSUE THREAD

**Issue by ntrrgc** [koush/ion#582]
After looking at the open and closed issues I'm not sure about whether SNI works with ion or not and under what conditions. 

I would be grateful if this was clarified in the README.

**Comment by koush** [comment]
Yes, works if linked to GMS or Lollipop onwards.

**Comment by ntrrgc** [comment]
What does *linked to GMS* mean?

**Comment by koush** [comment]
linked to google play services.

com.google.android.gms:play-services-base:7.5.0
 I think

**Comment by ntrrgc** [comment]
Why does it matter? How can the inner HTTP library change whether your application is or not in Google Play?

**Comment by coolya** [comment]
ION uses the crypto libraries on the device to make tls connections. If those library supper SNI than ION can use it otherwise not. 
The onboard android crypto libs [support SNI since 4.0](https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=4.0.4).
If your device is prior to that you have to use google play services because they add additional crypo capabilities to the device.

**Comment by koush** [comment]
Google Play ships a unbundled version of openssl that is kept up to date with google play service updates. It also has newer features that are not available depending on the android platform version.

https://developer.android.com/training/articles/security-gms-provider.html

**Comment by ntrrgc** [comment]
Ok, so actually SNI is supported in Android 4.0+ and in older versions using those patches. Thanks for the help.
