### ISSUE TITLE
Use Ion in an IntentService

### ISSUE THREAD

**Issue by jirevwe** [koush/ion#651]
Hi,
I have this code

```
Ion.getDefault(this).configure().setLogging("ion-sample", Log.DEBUG);
    Ion.with(this)
            .load("http://www.mp3123.com/english/Fall%20Out%20Boy%20-%20Immortals%20-%20Mp3Visit.Com.mp3")
            .progress(new ProgressCallback() {
                @Override
                public void onProgress(long downloaded, long total) {
                    Log.e("Download Progress", downloaded + "/" + total);
                    mBuilder.setProgress((int)total, (int)downloaded, false);
                    mNotifyManager.notify(1, mBuilder.build());
                }
            })
            .write(file)
            .setCallback(new FutureCallback<File>() {
                @Override
                public void onCompleted(Exception e, File result) {
                    if(e == null)
                    {
                        mBuilder.setContentText("Download complete").setProgress(0, 0, false);
                        mNotifyManager.notify(1, mBuilder.build());
                    }
                }
            });
```

When I run this in an activity and close the activity, the download cancels.
Can I run this in an IntentService? Because I know that both Ion and IntentServices run on another thread.

thanks.

**Comment by Jjastiny** [comment]
yes i believe u can run it on intent service and ion but i think u are killing the app process and it will kill all the intent service as well. (this is when u press the square button and press kill all app) And to fix this u would override ontaskremoved and restart the intentservice. Hopefully this helps

**Comment by kingsleyadio** [comment]
From your description, I figured you are trying to keep the download running in the background even after the app is closed. Yes, you can make use of an intent service. However, you will need to make a little adjustment. Instead of setting a callback as you have done, you would use the `.get` method instead, which effectively blocks the IntentService handler thread until the download is finished, otherwise, the method returns immediately, and the download is again canceled.
Instead, you could extend Service directly, setup your own handler thread and you can manually exit the service once the download is complete.

Hope that helps

**Comment by jirevwe** [comment]
@Jjastiny I didn't see you reply early enough.
@kingsleyadio I'll try that 
I already solved the problem using DownloadManger. I'll still revisit the code. I'm coding other parts of the app for now. Thanks. Hopefully this helps  other people.

**Comment by angryanatole** [comment]
@kingsleyadio thanks for your reply, I had the same problem and it really helped.
