### ISSUE TITLE
Random NullPointerException behind proxy

### ISSUE THREAD

**Issue by r4m** [koush/ion#95]
Hi @koush, your lib is great. However I've found that if I instantiate `Ion` behind a proxy, let say CharlesProxy, setting a FutureCallback with Response, i.e.

``` java
Ion.with(this, url)
                .proxy(Constants.CHARLES_PROXY_SERVER, 8888)
                .asJsonObject()
                .withResponse()
                .setCallback(new FutureCallback<Response<JsonObject>>() {
                    @Override
                    public void onCompleted(Exception e, Response<JsonObject> result) {
                        if (result.getHeaders().getResponseCode() == HttpStatus.SC_OK)
                        {
                            if (!result.getResult().isJsonNull())
                            {
                                   // Do stuff here
                            }
                        }
                });
```

random NullPointerExceptions take place regarding the `getResult()` of the `Response`. Precisely the `result` becomes `null` after verifying that the response code is OK. I'm sure that the json content is not null and I've tried the above setup with CharlesProxy attached or not to the `Ion` instance. If CharlesProxy is not enabled everything works fine.

If it could be helpful I've also noticed that the server, even returning a 200 status code, it is giving me the following error if CharlesProxy is enabled: `SSL_write: bad write retry (OpenSSL::SSL::SSLError)`.

**Comment by maurermax** [comment]
unearthing this again as I have it now. Indeed the NPE happens outside of the ion lib. But the problem is due to charles returning complaints about the request itself which is compiled by ion.

In my case charles does not proxy the request and instead returns

````
<h1>Charles Error Report</h1>
<h2>Failure</h2>
<p>Malformed request URL &quot;&#x2F;eSCL&#x2F;ScannerStatus&quot;. Consider enabling Transparent proxying.</p>
<p>The actual exception reported was:</p>
<pre>
com.xk72.proxy.ProxyException: Malformed request URL &quot;&#x2F;eSCL&#x2F;ScannerStatus&quot;. Consider enabling Transparent proxying.
</pre>
````

don't know how the URL can be illegal. First I thought for IP connections it is missing the Host value to do its proxying but then I found that it seems that proxy servers need full URLs instead of relative URLs? Is that true? This might very well be a ion issue then....
